apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app.kubernetes.io/name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
    spec:
      containers:
      - name: hello
        image: hello:v2
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hello
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
